### ISSUE TITLE
Idea: Vis editor bindings

### ISSUE THREAD

**Issue by jgarte** [Russoul/Idris2-Lua#8]
Hi, could this project be used to interface with the [vis editor API](https://martanne.github.io/vis/doc/)?

Trying to brainstorm a use case for it.

Any advice or insight much appreciated.

**Comment by Russoul** [comment]
I am pretty confident that it can interface with any project that is based on a supported Lua version, that is: 5.1, 5.2, 5.3 and luajit (recent versions of it, AFAICR)

There are a few examples of writing an FFI layer in tests.
Also this project might come in handy as a source of examples of writing FFI:
https://github.com/ShinKage/nvim-idris2

It's been a while since the last time I compiled that project. It's been superseded by Idris2-LSP

Idris2 version supported by Idris2-Lua is falling behind...
I'll try to update to Idris2-0.5.X in the meantime.

**Comment by Russoul** [comment]
Updated the project to Idris 2-0.5.1 (most recent commit as to 28 Oct)
There is a problem on CI's Ubuntu installation I haven't solved. But it's irrelevant to Idris2-Lua semantics. 

Feel free to ask on github or Idris' discord channel if you have any questions / issues.

**Comment by jgarte** [comment]
Thanks for doing that and for pointing me to some resources. Will do.
